### PR TITLE
XRNX plugin

### PR DESCRIPTION
**Pull request by asbjornu**
I've created a basic XRNX plugin that hooks into the `app_new_document` and `app_saved_document` notifiers. It doesn't do much else useful yet, but I have had a look at adding [LuaGit](/libgit2/luagit2) and it unfortunately doesn't seem trivial to just drop it into the plugin without requiring anything installed on the computer. We need to explore that in more detail.

### CODE REVIEW

**Comment by asbjornu** [comment]
As an alternative to the [LibGit](https://libgit2.github.com/) (which is written in C and therefore needs to be wrapped) based LuaGit, there are all-Lua alternatives like [this](/creationix/lua-git) and [this](/mkottman/lua-git). They seem incomplete and rought, but might just have enough functionality for what we need here. They will also have a greater chance of working cross platform, I think.

**Comment by asbjornu** [comment]
Please read [this](/renoise/xrnx) on how to do development in Renoise. The simplest way is to find the `config.xml` file from the preferences folder, and set the `ShowScriptingDevelopmentTools` property to `true`. From there, you can just drag and drop any folder with a name ending with `.xrnx` on top of Renoise, and it will think it's a plugin and install it.

Installing will actually copy the files into Renoise's Library folder, so you will need to either continue hacking inside the Library folder, set up your git repository there, or uninstall and reinstall every time you want to make a change. I haven't figured out the best workflow yet.

**Comment by Neurogami** [comment]
I don't understand this pull request.  If there is to be a Lua/xrnx version it should be in a separate project. 

rnsgit is a standalone command-line tool.  Having a single repo that is both a ruby-based CLI tool and a seperate Lua-based Renoise tool is confusing.

**Comment by asbjornu** [comment]
I agree that having a single repository maintaining two separate languages doesn't make sense. I'm sorry, but I got the impression that you would like to move the project from Ruby and CLI to Lua and XRNX. I take it from your comment and rejection that I've misunderstood?

**Pull request closed without merging**
